apiVersion: v1
data:
  token: NDdkNTYwNTY1NWI4M2YyNTFiMWE5YzljZTRhMzVkMDg4ZjMyODc2YzMxZDljZGNlZGY0NTU4MTRlM2ZmYzE0Yw==
kind: Secret
metadata:
  name: do-token
  namespace: {{ .Release.Namespace }}
type: Opaque
