{{ if false }}
apiVersion: v1
kind: Service
metadata:
  name: foo
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  clusterIPs:
  - None
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 80
  sessionAffinity: None
  type: ClusterIP
{{ end }}
